# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitch" do
  name "gitch"
  desc "Git identity manager - never commit with the wrong identity again"
  homepage "https://github.com/orzazade/gitch"
  version "2.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitch"

  on_macos do
    on_intel do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_darwin_amd64.tar.gz"
      sha256 "b91df13a764ae5a5a63e3e0003db9609c77b82f90f02e8713665a63241c75847"
    end
    on_arm do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_darwin_arm64.tar.gz"
      sha256 "f25dfc2783e6b350c0749cf3d40afbc9af18aa320f52d2825e6c56e2c0abd1e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_linux_amd64.tar.gz"
      sha256 "da00d4c73d08e30fd2f574afb1f9cec101652b19470878670d01b4ad2b42ca75"
    end
    on_arm do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_linux_arm64.tar.gz"
      sha256 "ec894f296935597a99e1f68a22613514a50fbb0d5bf7178748eec3b7bc169387"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitch"]
  end

  # No zap stanza required
end
