# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitch" do
  name "gitch"
  desc "Git identity manager - never commit with the wrong identity again"
  homepage "https://github.com/orzazade/gitch"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitch"

  on_macos do
    on_intel do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_darwin_amd64.tar.gz"
      sha256 "894ab64f14bde9f989571fd9c6d92dca85e06ad046b7913dc7dfc1be570eb29f"
    end
    on_arm do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_darwin_arm64.tar.gz"
      sha256 "2afc40516333cde86372ac34073628702a527790e2596d022895410b7bbabd49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_linux_amd64.tar.gz"
      sha256 "350fff921d19d851c52a5ef3baa001405f518be43322f2fba49f02df15c25228"
    end
    on_arm do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_linux_arm64.tar.gz"
      sha256 "694d6fa66651153b322ba491d9ee2267012d8d1ea35997d4e6b64442d4c94fd4"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitch"]
  end

  # No zap stanza required
end
