# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitch" do
  name "gitch"
  desc "Git identity manager - never commit with the wrong identity again"
  homepage "https://github.com/orzazade/gitch"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitch"

  on_macos do
    on_intel do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_darwin_amd64.tar.gz"
      sha256 "5d3568b87efcefeb4cb8de95fc15dd76756fc2822c744fb9d9e05c02893a645d"
    end
    on_arm do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_darwin_arm64.tar.gz"
      sha256 "e54de9afba64a63c6e55fc432400aaa1ea7669b4584cb3b5ff713cf03a6c4ff3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_linux_amd64.tar.gz"
      sha256 "256bdca20e961558f49d67875d20e6cc18516fee09635424446a9a7f6cd6e24f"
    end
    on_arm do
      url "https://github.com/orzazade/gitch/releases/download/v#{version}/gitch_#{version}_linux_arm64.tar.gz"
      sha256 "fe50fc47033019d10dadf450948bc571dc160904c40aecdd26f7541e86cf0cc9"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitch"]
  end

  # No zap stanza required
end
